[package]
name = "advent"
version = "0.1.0"
authors = ["Alice"]
edition = "2018"

[dependencies]
regex = "1"
lazy_static = "1.3.0"

[lib]
name = "aoc"
path = "src/lib.rs"

[[bin]]
name="aoc_bin"
path = "src/bin.rs"